import PDFDocument from "pdfkit";

function bufferFromDoc(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}

// ── Drawing helpers ────────────────────────────────────────────────────────────

const BRAND = "#1a56db";
const MUTED = "#6b7280";
const BORDER = "#e5e7eb";
const TEXT = "#111827";
const PAGE_MARGIN = 48;

function header(doc: PDFKit.PDFDocument, title: string, subtitle: string) {
  doc.rect(0, 0, doc.page.width, 70).fill(BRAND);
  doc.fillColor("white").fontSize(20).font("Helvetica-Bold").text("360CRD", PAGE_MARGIN, 18);
  doc.fontSize(9).font("Helvetica").text("Compliance & Risk Dashboard", PAGE_MARGIN, 41);
  doc.fillColor(TEXT).fontSize(16).font("Helvetica-Bold").text(title, PAGE_MARGIN, 90);
  doc.fillColor(MUTED).fontSize(9).font("Helvetica").text(subtitle, PAGE_MARGIN, 112);
  doc.moveTo(PAGE_MARGIN, 130).lineTo(doc.page.width - PAGE_MARGIN, 130).strokeColor(BORDER).stroke();
  doc.y = 140;
}

function sectionTitle(doc: PDFKit.PDFDocument, text: string) {
  if (doc.y > doc.page.height - 120) doc.addPage();
  doc.moveDown(0.6);
  doc.fillColor(TEXT).fontSize(11).font("Helvetica-Bold").text(text, PAGE_MARGIN);
  doc.moveDown(0.3);
}

function statRow(doc: PDFKit.PDFDocument, label: string, value: string | number) {
  const y = doc.y;
  doc.fontSize(9).font("Helvetica-Bold").fillColor(MUTED).text(label, PAGE_MARGIN, y, { width: 220, continued: false });
  doc.fontSize(9).font("Helvetica").fillColor(TEXT).text(String(value), PAGE_MARGIN + 230, y);
  doc.y = y + 16;
}

function tableHeader(doc: PDFKit.PDFDocument, cols: string[], widths: number[]) {
  const y = doc.y;
  doc.rect(PAGE_MARGIN, y, cols.reduce((a, _, i) => a + widths[i], 0), 18).fill("#f3f4f6");
  let x = PAGE_MARGIN;
  cols.forEach((col, i) => {
    doc.fillColor(MUTED).fontSize(8).font("Helvetica-Bold").text(col, x + 4, y + 4, { width: widths[i] - 8, ellipsis: true });
    x += widths[i];
  });
  doc.y = y + 18;
}

function tableRow(doc: PDFKit.PDFDocument, cells: (string | number | null | undefined)[], widths: number[], even: boolean) {
  if (doc.y > doc.page.height - 80) doc.addPage();
  const y = doc.y;
  const totalW = widths.reduce((a, w) => a + w, 0);
  if (even) doc.rect(PAGE_MARGIN, y, totalW, 16).fill("#fafafa");
  let x = PAGE_MARGIN;
  cells.forEach((cell, i) => {
    const val = cell == null ? "—" : String(cell);
    doc.fillColor(TEXT).fontSize(8).font("Helvetica").text(val, x + 4, y + 3, { width: widths[i] - 8, ellipsis: true });
    x += widths[i];
  });
  doc.rect(PAGE_MARGIN, y, totalW, 16).strokeColor(BORDER).lineWidth(0.5).stroke();
  doc.y = y + 16;
}

function footer(doc: PDFKit.PDFDocument) {
  const pages = (doc.bufferedPageRange?.() as any)?.count ?? 1;
  for (let i = 0; i < pages; i++) {
    doc.switchToPage(i);
    doc
      .fillColor(MUTED)
      .fontSize(8)
      .font("Helvetica")
      .text(
        `Generated by 360CRD  •  ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}`,
        PAGE_MARGIN,
        doc.page.height - 32,
        { align: "left" },
      );
    doc.text(`Page ${i + 1} of ${pages}`, 0, doc.page.height - 32, { align: "right", width: doc.page.width - PAGE_MARGIN });
  }
}

// ── Type-specific renderers ────────────────────────────────────────────────────

function renderIncidentSummary(doc: PDFKit.PDFDocument, data: any) {
  const { incidents = [], summary } = data;

  sectionTitle(doc, "Summary");
  statRow(doc, "Total Incidents", summary?.total ?? incidents.length);
  if (summary?.bySeverity) {
    summary.bySeverity.forEach((r: any) => statRow(doc, `  Severity: ${r.severity}`, r._count));
  }
  if (summary?.byStatus) {
    summary.byStatus.forEach((r: any) => statRow(doc, `  Status: ${r.status}`, r._count));
  }

  if (incidents.length) {
    sectionTitle(doc, "Incidents");
    const cols = ["Title", "Severity", "Status", "Location", "Occurred At"];
    const widths = [165, 75, 75, 110, 90];
    tableHeader(doc, cols, widths);
    incidents.slice(0, 200).forEach((inc: any, i: number) => {
      tableRow(
        doc,
        [
          inc.title,
          inc.severity,
          inc.status,
          inc.location ?? inc.locationId ?? "—",
          inc.occurredAt ? new Date(inc.occurredAt).toLocaleDateString("en-GB") : "—",
        ],
        widths,
        i % 2 === 0,
      );
    });
  }
}

function renderAuditSummary(doc: PDFKit.PDFDocument, data: any) {
  const { audits = [], total } = data;

  sectionTitle(doc, "Summary");
  statRow(doc, "Total Audits", total ?? audits.length);

  if (audits.length) {
    sectionTitle(doc, "Audits");
    const cols = ["Title", "Type", "Status", "Passed", "Score %", "Due Date"];
    const widths = [155, 80, 75, 50, 55, 90];
    tableHeader(doc, cols, widths);
    audits.slice(0, 200).forEach((a: any, i: number) => {
      tableRow(
        doc,
        [
          a.title,
          a.type,
          a.status,
          a.passed ? "Yes" : "No",
          a.percentage != null ? a.percentage : "—",
          a.dueDate ? new Date(a.dueDate).toLocaleDateString("en-GB") : "—",
        ],
        widths,
        i % 2 === 0,
      );
    });
  }
}

function renderTrainingCompletion(doc: PDFKit.PDFDocument, data: any) {
  const { enrollments = [], summary } = data;

  sectionTitle(doc, "Summary");
  statRow(doc, "Total Enrollments", summary?.total ?? enrollments.length);
  if (summary?.byStatus) {
    Object.entries(summary.byStatus).forEach(([k, v]) => statRow(doc, `  ${k}`, v as number));
  }

  if (enrollments.length) {
    sectionTitle(doc, "Enrollments");
    const cols = ["Employee", "Email", "Training", "Status", "Enrolled At"];
    const widths = [110, 130, 130, 70, 75];
    tableHeader(doc, cols, widths);
    enrollments.slice(0, 200).forEach((e: any, i: number) => {
      tableRow(
        doc,
        [
          `${e.user?.firstName ?? ""} ${e.user?.lastName ?? ""}`.trim() || "—",
          e.user?.email ?? "—",
          e.training?.title ?? "—",
          e.status,
          e.enrolledAt ? new Date(e.enrolledAt).toLocaleDateString("en-GB") : "—",
        ],
        widths,
        i % 2 === 0,
      );
    });
  }
}

function renderPpeInventory(doc: PDFKit.PDFDocument, data: any) {
  const { items = [], total } = data;

  sectionTitle(doc, "Summary");
  statRow(doc, "Total PPE Items", total ?? items.length);

  if (items.length) {
    sectionTitle(doc, "PPE Items");
    const cols = ["Name", "Category", "Size", "Quantity", "Available", "Assigned To"];
    const widths = [120, 90, 55, 65, 65, 110];
    tableHeader(doc, cols, widths);
    items.slice(0, 200).forEach((item: any, i: number) => {
      const assigned = item.assignments?.map((a: any) => `${a.user?.firstName ?? ""} ${a.user?.lastName ?? ""}`.trim()).join(", ") ?? "—";
      tableRow(
        doc,
        [item.name, item.category ?? "—", item.size ?? "—", item.quantity ?? "—", item.availableQuantity ?? "—", assigned || "—"],
        widths,
        i % 2 === 0,
      );
    });
  }
}

function renderWasteSummary(doc: PDFKit.PDFDocument, data: any) {
  const { records = [], summary } = data;

  sectionTitle(doc, "Summary");
  statRow(doc, "Total Records", summary?.total ?? records.length);
  if (summary?.totalQuantity != null) statRow(doc, "Total Quantity", summary.totalQuantity);
  if (summary?.totalCost != null) statRow(doc, "Total Cost", summary.totalCost);
  if (summary?.byCategory) {
    summary.byCategory.forEach((r: any) => statRow(doc, `  Category: ${r.category}`, `${r._count} records, ${r._sum?.quantity ?? 0} qty`));
  }

  if (records.length) {
    sectionTitle(doc, "Waste Records");
    const cols = ["Type", "Category", "Quantity", "Unit", "Site", "Disposed At"];
    const widths = [110, 90, 65, 55, 100, 95];
    tableHeader(doc, cols, widths);
    records.slice(0, 200).forEach((rec: any, i: number) => {
      tableRow(
        doc,
        [
          rec.wasteType ?? rec.type ?? "—",
          rec.category ?? "—",
          rec.quantity ?? "—",
          rec.unit ?? "—",
          rec.site?.name ?? "—",
          rec.disposedAt ? new Date(rec.disposedAt).toLocaleDateString("en-GB") : "—",
        ],
        widths,
        i % 2 === 0,
      );
    });
  }
}

function renderComplianceStatus(doc: PDFKit.PDFDocument, data: any) {
  sectionTitle(doc, "Compliance Overview");
  statRow(doc, "Overall Compliance Score", `${data.complianceScore ?? 0}%`);
  statRow(doc, "Overdue Audits", data.overdueAudits ?? 0);
  statRow(doc, "Open Incidents", data.openIncidents ?? 0);
  statRow(doc, "Training Completion Rate", `${data.trainingCompletionRate ?? 0}%`);
  statRow(doc, "Induction Completion Rate", `${data.inductionCompletionRate ?? 0}%`);
}

// ── Public API ─────────────────────────────────────────────────────────────────

export async function generateReportPdf(report: {
  id: string;
  title: string;
  type: string;
  generatedAt: Date | null;
}, data: any): Promise<Buffer> {
  const doc = new PDFDocument({ margin: PAGE_MARGIN, size: "A4", bufferPages: true });
  const bufferPromise = bufferFromDoc(doc);

  const typeLabel = report.type.replace(/_/g, " ");
  const generatedAt = report.generatedAt
    ? new Date(report.generatedAt).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })
    : new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });

  header(doc, report.title, `${typeLabel}  •  Generated: ${generatedAt}`);

  switch (report.type) {
    case "INCIDENT_SUMMARY":    renderIncidentSummary(doc, data);    break;
    case "AUDIT_SUMMARY":       renderAuditSummary(doc, data);       break;
    case "TRAINING_COMPLETION": renderTrainingCompletion(doc, data); break;
    case "PPE_INVENTORY":       renderPpeInventory(doc, data);       break;
    case "WASTE_SUMMARY":       renderWasteSummary(doc, data);       break;
    case "COMPLIANCE_STATUS":   renderComplianceStatus(doc, data);   break;
    default:
      sectionTitle(doc, "Data");
      doc.fontSize(9).font("Helvetica").fillColor(TEXT).text(JSON.stringify(data, null, 2), PAGE_MARGIN);
  }

  footer(doc);
  doc.end();
  return bufferPromise;
}
