/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPortalSitesRouteImport } from './routes/_authenticated/portal/sites'
import { Route as AuthenticatedPortalReportsRouteImport } from './routes/_authenticated/portal/reports'
import { Route as AuthenticatedPortalNotificationsRouteImport } from './routes/_authenticated/portal/notifications'
import { Route as AuthenticatedPortalIncidentsRouteImport } from './routes/_authenticated/portal/incidents'
import { Route as AuthenticatedPortalFeedbackRouteImport } from './routes/_authenticated/portal/feedback'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal/documents'
import { Route as AuthenticatedPortalDashboardRouteImport } from './routes/_authenticated/portal/dashboard'
import { Route as AuthenticatedPortalAuditsRouteImport } from './routes/_authenticated/portal/audits'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalSitesRoute =
  AuthenticatedPortalSitesRouteImport.update({
    id: '/sites',
    path: '/sites',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalReportsRoute =
  AuthenticatedPortalReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalNotificationsRoute =
  AuthenticatedPortalNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalIncidentsRoute =
  AuthenticatedPortalIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalFeedbackRoute =
  AuthenticatedPortalFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDashboardRoute =
  AuthenticatedPortalDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAuditsRoute =
  AuthenticatedPortalAuditsRouteImport.update({
    id: '/audits',
    path: '/audits',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/portal/audits': typeof AuthenticatedPortalAuditsRoute
  '/portal/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/feedback': typeof AuthenticatedPortalFeedbackRoute
  '/portal/incidents': typeof AuthenticatedPortalIncidentsRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/portal/sites': typeof AuthenticatedPortalSitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/portal/audits': typeof AuthenticatedPortalAuditsRoute
  '/portal/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/feedback': typeof AuthenticatedPortalFeedbackRoute
  '/portal/incidents': typeof AuthenticatedPortalIncidentsRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/portal/sites': typeof AuthenticatedPortalSitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/portal/audits': typeof AuthenticatedPortalAuditsRoute
  '/_authenticated/portal/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/feedback': typeof AuthenticatedPortalFeedbackRoute
  '/_authenticated/portal/incidents': typeof AuthenticatedPortalIncidentsRoute
  '/_authenticated/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/_authenticated/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/_authenticated/portal/sites': typeof AuthenticatedPortalSitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/portal'
    | '/portal/audits'
    | '/portal/dashboard'
    | '/portal/documents'
    | '/portal/feedback'
    | '/portal/incidents'
    | '/portal/notifications'
    | '/portal/reports'
    | '/portal/sites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/portal'
    | '/portal/audits'
    | '/portal/dashboard'
    | '/portal/documents'
    | '/portal/feedback'
    | '/portal/incidents'
    | '/portal/notifications'
    | '/portal/reports'
    | '/portal/sites'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/portal'
    | '/_authenticated/portal/audits'
    | '/_authenticated/portal/dashboard'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/feedback'
    | '/_authenticated/portal/incidents'
    | '/_authenticated/portal/notifications'
    | '/_authenticated/portal/reports'
    | '/_authenticated/portal/sites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/sites': {
      id: '/_authenticated/portal/sites'
      path: '/sites'
      fullPath: '/portal/sites'
      preLoaderRoute: typeof AuthenticatedPortalSitesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/reports': {
      id: '/_authenticated/portal/reports'
      path: '/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof AuthenticatedPortalReportsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/notifications': {
      id: '/_authenticated/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof AuthenticatedPortalNotificationsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/incidents': {
      id: '/_authenticated/portal/incidents'
      path: '/incidents'
      fullPath: '/portal/incidents'
      preLoaderRoute: typeof AuthenticatedPortalIncidentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/feedback': {
      id: '/_authenticated/portal/feedback'
      path: '/feedback'
      fullPath: '/portal/feedback'
      preLoaderRoute: typeof AuthenticatedPortalFeedbackRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/dashboard': {
      id: '/_authenticated/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof AuthenticatedPortalDashboardRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/audits': {
      id: '/_authenticated/portal/audits'
      path: '/audits'
      fullPath: '/portal/audits'
      preLoaderRoute: typeof AuthenticatedPortalAuditsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
  }
}

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAuditsRoute: typeof AuthenticatedPortalAuditsRoute
  AuthenticatedPortalDashboardRoute: typeof AuthenticatedPortalDashboardRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalFeedbackRoute: typeof AuthenticatedPortalFeedbackRoute
  AuthenticatedPortalIncidentsRoute: typeof AuthenticatedPortalIncidentsRoute
  AuthenticatedPortalNotificationsRoute: typeof AuthenticatedPortalNotificationsRoute
  AuthenticatedPortalReportsRoute: typeof AuthenticatedPortalReportsRoute
  AuthenticatedPortalSitesRoute: typeof AuthenticatedPortalSitesRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAuditsRoute: AuthenticatedPortalAuditsRoute,
  AuthenticatedPortalDashboardRoute: AuthenticatedPortalDashboardRoute,
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalFeedbackRoute: AuthenticatedPortalFeedbackRoute,
  AuthenticatedPortalIncidentsRoute: AuthenticatedPortalIncidentsRoute,
  AuthenticatedPortalNotificationsRoute: AuthenticatedPortalNotificationsRoute,
  AuthenticatedPortalReportsRoute: AuthenticatedPortalReportsRoute,
  AuthenticatedPortalSitesRoute: AuthenticatedPortalSitesRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
